// Automatically generated by MockGen. DO NOT EDIT!
// Source: ./hooks/prehooks.go

package mocks

import (
	gomock "code.google.com/p/gomock/gomock"
)

// Mock of Prehooker interface
type MockPrehooker struct {
	ctrl     *gomock.Controller
	recorder *_MockPrehookerRecorder
}

// Recorder for MockPrehooker (not exported)
type _MockPrehookerRecorder struct {
	mock *MockPrehooker
}

func NewMockPrehooker(ctrl *gomock.Controller) *MockPrehooker {
	mock := &MockPrehooker{ctrl: ctrl}
	mock.recorder = &_MockPrehookerRecorder{mock}
	return mock
}

func (_m *MockPrehooker) EXPECT() *_MockPrehookerRecorder {
	return _m.recorder
}

func (_m *MockPrehooker) RunPrehook(uploadFiles []string) ([]string, error) {
	ret := _m.ctrl.Call(_m, "RunPrehook", uploadFiles)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockPrehookerRecorder) RunPrehook(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "RunPrehook", arg0)
}
