// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/imosquera/uploadthis/upload (interfaces: Uploader)

package mocks

import (
	gomock "code.google.com/p/gomock/gomock"
)

// Mock of Uploader interface
type MockUploader struct {
	ctrl     *gomock.Controller
	recorder *_MockUploaderRecorder
}

// Recorder for MockUploader (not exported)
type _MockUploaderRecorder struct {
	mock *MockUploader
}

func NewMockUploader(ctrl *gomock.Controller) *MockUploader {
	mock := &MockUploader{ctrl: ctrl}
	mock.recorder = &_MockUploaderRecorder{mock}
	return mock
}

func (_m *MockUploader) EXPECT() *_MockUploaderRecorder {
	return _m.recorder
}

func (_m *MockUploader) Upload(_param0 string) {
	_m.ctrl.Call(_m, "Upload", _param0)
}

func (_mr *_MockUploaderRecorder) Upload(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Upload", arg0)
}
